<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Home page</title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />
</head>
<body>
<div id="content" role="main">
    <section class="row colset-2-its">
        <h1>Welcome <sec:username /></h1>
        <p>
        <table border="1">
            <tr>
                <td><b>Pipeline</b></td>
                <td><b>Description</b></td>
            </tr>
            <tr>
                <td><g:link controller="amplicon"><asset:image src="ampliconIcon.png" height="80" width="80"/></g:link></td>
                <td>Amplicon pipeline to efficiently and reproducibly process data generated by next
                generation sequencing of complex microbial communities to derive a quantitative
                taxonomic overview.<br>
                For more information check the manual tab.</td>
            </tr>
        </table>
    </p>
    </section>
</div>
</body>
</html>